import dotenv from "dotenv";
import mongoose from "mongoose";
import bcrypt from "bcrypt";
import User from "../models/User.js";
import Agency from "../models/Agency.js";
import Property from "../models/Property.js";
import Country from "../models/Country.js";

dotenv.config();

const seedData = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log("✅ Connected to MongoDB");

    // Clear existing data
    await User.deleteMany({});
    await Agency.deleteMany({});
    await Property.deleteMany({});
    await Country.deleteMany({});
    console.log("🗑️  Cleared existing data");

    // Create countries
    const countries = await Country.create([
      { name: "USA", currency: "USD" },
      { name: "UK", currency: "GBP" },
      { name: "UAE", currency: "AED" },
      { name: "India", currency: "INR" },
    ]);
    console.log(`🌍 ${countries.length} countries created`);

    // Create admin user
    const adminPassword = await bcrypt.hash("Admin@123", 10);
    const admin = await User.create({
      name: "Admin User",
      email: "admin@demo.com",
      phone: "+1234567890",
      passwordHash: adminPassword,
      role: "ADMIN",
    });
    console.log("👤 Admin user created: admin@demo.com / Admin@123");

    // Create sample customer
    const customerPassword = await bcrypt.hash("Customer@123", 10);
    const customer = await User.create({
      name: "John Doe",
      email: "customer@demo.com",
      phone: "+1234567891",
      passwordHash: customerPassword,
      role: "CUSTOMER",
    });
    console.log("👤 Customer user created: customer@demo.com / Customer@123");

    // Create sample agencies
    const agencyPassword = await bcrypt.hash("Agency@123", 10);

    const agencies = await Agency.create([
      {
        name: "Global SIM Solutions",
        email: "sim@demo.com",
        passwordHash: agencyPassword,
        category: ["sim"],
        about:
          "We provide international SIM cards and mobile connectivity solutions for travelers. Stay connected in over 190 countries with our reliable network coverage and affordable data plans.",
        phone: "+1-555-0101",
        website: "https://globalsim.example.com",
        address: "123 Tech Plaza, Suite 200",
        city: "New York",
        country: "USA",
        logoUrl:
          "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop",
        images: [
          {
            url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "services",
          },
        ],
        isApproved: true,
      },
      {
        name: "SecureBank International",
        email: "bank@demo.com",
        passwordHash: agencyPassword,
        category: ["bank"],
        about:
          "International banking services for expatriates and digital nomads. Multi-currency accounts, low fees, and 24/7 customer support. Trusted by over 100,000 customers worldwide.",
        phone: "+44-20-7946-0958",
        website: "https://securebank.example.com",
        address: "456 Financial District, Canary Wharf",
        city: "London",
        country: "UK",
        logoUrl:
          "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=400&h=400&fit=crop",
        images: [
          {
            url: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "office",
          },
        ],
        isApproved: true,
      },
      {
        name: "TravelGuard Insurance",
        email: "insurance@demo.com",
        passwordHash: agencyPassword,
        category: ["insurance"],
        about:
          "Comprehensive travel and health insurance for international travelers. Coverage includes medical emergencies, trip cancellation, lost luggage, and adventure sports. Get instant quotes and claims processing.",
        phone: "+1-416-555-0123",
        website: "https://travelguard.example.com",
        address: "789 Insurance Tower, Bay Street",
        city: "Toronto",
        country: "Canada",
        logoUrl:
          "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400&h=400&fit=crop",
        images: [
          {
            url: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1554224154-26032844c514?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "reception",
          },
        ],
        isApproved: true,
      },
      {
        name: "FastVisa Services",
        email: "visa@demo.com",
        passwordHash: agencyPassword,
        category: ["visa"],
        about:
          "Quick and reliable visa processing services for all countries. Expert guidance, fast turnaround times, and 99% approval rate. We handle everything from document preparation to embassy submissions.",
        phone: "+971-4-555-0123",
        website: "https://fastvisa.example.com",
        address: "321 Embassy District, Business Bay",
        city: "Dubai",
        country: "UAE",
        logoUrl:
          "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=400&h=400&fit=crop",
        images: [
          {
            url: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "services",
          },
        ],
        isApproved: true,
      },
      {
        name: "Wanderlust Travel Agency",
        email: "travel@demo.com",
        passwordHash: agencyPassword,
        category: ["travel"],
        about:
          "Curated travel experiences and tour packages worldwide. From luxury getaways to budget adventures, we design personalized itineraries. Over 15 years of experience creating unforgettable journeys.",
        phone: "+1-212-555-0123",
        website: "https://wanderlust.example.com",
        address: "555 Broadway, Suite 200",
        city: "New York",
        country: "USA",
        logoUrl:
          "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=400&h=400&fit=crop",
        images: [
          {
            url: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "office",
          },
        ],
        isApproved: true,
      },
      {
        name: "Elite Realty Group",
        email: "elite@demo.com",
        passwordHash: agencyPassword,
        category: ["property"],
        about:
          "Premium real estate services in the United States. Specializing in luxury properties, investment opportunities, and relocation services. Our expert team provides personalized service to help you find your dream home.",
        phone: "+1-310-555-0123",
        website: "https://eliterealty.example.com",
        address: "456 Sunset Boulevard, Suite 500",
        city: "Los Angeles",
        country: "USA",
        logoUrl:
          "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=400&h=400&fit=crop",
        images: [
          {
            url: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "office",
          },
        ],
        isApproved: true,
      },
      {
        name: "London Property Partners",
        email: "london@demo.com",
        passwordHash: agencyPassword,
        category: ["property"],
        about:
          "Established real estate agency serving London and surrounding areas. We offer comprehensive property services including sales, lettings, and property management. Trusted by thousands of clients across the UK.",
        phone: "+44-20-7946-0123",
        website: "https://londonproperty.example.com",
        address: "123 Mayfair Square",
        city: "London",
        country: "UK",
        logoUrl:
          "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=400&h=400&fit=crop",
        images: [
          {
            url: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "reception",
          },
        ],
        isApproved: true,
      },
      {
        name: "Dubai Luxury Properties",
        email: "dubai@demo.com",
        passwordHash: agencyPassword,
        category: ["property"],
        about:
          "Exclusive real estate agency specializing in luxury properties in Dubai and UAE. From penthouses to villas, we offer the finest selection of premium properties with world-class amenities and stunning views.",
        phone: "+971-4-555-0124",
        website: "https://dubailuxury.example.com",
        address: "456 Sheikh Zayed Road, Business Bay",
        city: "Dubai",
        country: "UAE",
        logoUrl:
          "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=400&h=400&fit=crop",
        images: [
          {
            url: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "office",
          },
        ],
        isApproved: true,
      },
      {
        name: "India Property Experts",
        email: "property@demo.com",
        passwordHash: agencyPassword,
        category: ["property"],
        about:
          "Leading real estate agency in India specializing in premium residential and commercial properties. Over 20 years of experience helping clients find their perfect home or investment property across major Indian cities.",
        phone: "+91-22-5555-0123",
        website: "https://indiaproperty.example.com",
        address: "789 Business Tower, Bandra Kurla Complex",
        city: "Mumbai",
        country: "India",
        logoUrl:
          "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=400&h=400&fit=crop",
        images: [
          {
            url: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "other",
          },
        ],
        isApproved: true,
      },
      {
        name: "UK Relocation Services",
        email: "relocation@demo.com",
        passwordHash: agencyPassword,
        category: ["relocation"],
        about:
          "Complete relocation services for individuals and families moving to the UK. We assist with visa processing, housing, school enrollment, and settling-in services. Making your move to the UK seamless and stress-free.",
        phone: "+44-20-7946-0456",
        website: "https://ukrelocation.example.com",
        address: "321 Oxford Street",
        city: "London",
        country: "UK",
        logoUrl:
          "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=400&h=400&fit=crop",
        images: [
          {
            url: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "meeting-room",
          },
        ],
        isApproved: true,
      },
      {
        name: "UAE Business Services",
        email: "business@demo.com",
        passwordHash: agencyPassword,
        category: ["business"],
        about:
          "Comprehensive business setup and consulting services in the UAE. We help entrepreneurs and companies establish their presence in Dubai and Abu Dhabi with company registration, licensing, and ongoing support.",
        phone: "+971-4-555-0456",
        website: "https://uaebusiness.example.com",
        address: "789 Business Center, DIFC",
        city: "Dubai",
        country: "UAE",
        logoUrl:
          "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=400&h=400&fit=crop",
        images: [
          {
            url: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "facilities",
          },
        ],
        isApproved: true,
      },
      {
        name: "Mumbai Real Estate Solutions",
        email: "mumbai@demo.com",
        passwordHash: agencyPassword,
        category: ["property"],
        about:
          "Premier real estate consultancy in Mumbai. Specializing in residential and commercial properties across South Mumbai, Bandra, and Powai. Expert guidance for buying, selling, and renting properties in India's financial capital.",
        phone: "+91-22-6666-0123",
        website: "https://mumbairealestate.example.com",
        address: "123 Marine Drive, Colaba",
        city: "Mumbai",
        country: "India",
        logoUrl:
          "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=400&h=400&fit=crop",
        images: [
          {
            url: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "facilities",
          },
        ],
        isApproved: true,
      },
    ]);
    console.log(
      `🏢 ${agencies.length} agencies created (all with password: Agency@123)`
    );

    // Create sample properties with photo objects
    const properties = await Property.create([
      {
        ownerType: "User",
        owner: customer._id,
        title: "Modern Studio in Manhattan",
        description:
          "Beautiful studio apartment in the heart of Manhattan with amazing city views. Fully furnished with modern amenities, high-speed WiFi, and access to building gym and rooftop terrace. Perfect for professionals and digital nomads. Located in SoHo, walking distance to subway, restaurants, and shopping.",
        price: 2500,
        currency: "USD",
        city: "New York",
        country: "USA",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "kitchen",
          },
        ],
        bedrooms: 0,
        bathrooms: 1,
        area: 450,
        areaUnit: "sqft",
        propertyType: "studio",
        amenities: ["WiFi", "Gym", "Rooftop", "Air Conditioning", "Dishwasher"],
        furnished: true,
        petsAllowed: false,
        availableFrom: new Date("2024-02-01"),
        latitude: 40.7231,
        longitude: -74.0026,
        featured: true,
        active: true,
      },
      {
        ownerType: "User",
        owner: customer._id,
        title: "Cozy Apartment in London",
        description:
          "Charming 2-bedroom apartment near Hyde Park. Victorian building with modern interior, fully equipped kitchen, and private balcony. Quiet residential area with excellent transport links. Perfect for families or professionals seeking a peaceful retreat in central London.",
        price: 2000,
        currency: "GBP",
        city: "London",
        country: "UK",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1505843513577-22bb7d21e455?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bathroom",
          },
        ],
        bedrooms: 2,
        bathrooms: 1,
        area: 750,
        areaUnit: "sqft",
        propertyType: "apartment",
        amenities: [
          "WiFi",
          "Balcony",
          "Dishwasher",
          "Washing Machine",
          "Heating",
        ],
        furnished: true,
        petsAllowed: true,
        availableFrom: new Date("2024-02-15"),
        latitude: 51.5074,
        longitude: -0.1278,
        featured: false,
        active: true,
      },
      {
        ownerType: "Agency",
        owner: agencies[4]._id,
        title: "Luxury Villa in Dubai",
        description:
          "Stunning 4-bedroom villa with private pool and beach access. Ultra-modern design with floor-to-ceiling windows, marble finishes, and smart home technology. Located in Palm Jumeirah with direct beach access. Includes private parking, security, and concierge services.",
        price: 8000,
        currency: "AED",
        city: "Dubai",
        country: "UAE",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bathroom",
          },
        ],
        bedrooms: 4,
        bathrooms: 4,
        area: 3500,
        areaUnit: "sqft",
        propertyType: "villa",
        amenities: [
          "Pool",
          "Beach Access",
          "Parking",
          "Security",
          "Concierge",
          "Smart Home",
          "Gym",
          "WiFi",
        ],
        furnished: true,
        petsAllowed: false,
        availableFrom: new Date("2024-03-01"),
        latitude: 25.1124,
        longitude: 55.139,
        featured: true,
        active: true,
      },
      {
        ownerType: "Agency",
        owner: agencies[4]._id,
        title: "Penthouse in Singapore",
        description:
          "Ultra-modern penthouse with panoramic city views. Spacious 3-bedroom unit on the 45th floor with private terrace, infinity pool, and premium finishes. Located in Marina Bay area with world-class amenities including gym, spa, and 24/7 concierge.",
        price: 5000,
        currency: "SGD",
        city: "Mumbai",
        country: "India",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
        ],
        bedrooms: 3,
        bathrooms: 3,
        area: 2200,
        areaUnit: "sqft",
        propertyType: "condo",
        amenities: [
          "Pool",
          "Gym",
          "Spa",
          "Concierge",
          "Parking",
          "Terrace",
          "WiFi",
          "Smart Home",
        ],
        furnished: true,
        petsAllowed: false,
        availableFrom: new Date("2024-02-20"),
        latitude: 1.2801,
        longitude: 103.8509,
        featured: true,
        active: true,
      },
      {
        ownerType: "User",
        owner: customer._id,
        title: "Beach House in Bali",
        description:
          "Relaxing beach house perfect for digital nomads. Traditional Balinese design meets modern comfort. Steps from the beach, with outdoor workspace, fast WiFi, and stunning ocean views. Surrounded by rice paddies and tropical gardens. Ideal for remote workers seeking inspiration.",
        price: 1200,
        currency: "USD",
        city: "Bali",
        country: "Indonesia",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "living-room",
          },
        ],
        bedrooms: 2,
        bathrooms: 2,
        area: 1200,
        areaUnit: "sqft",
        propertyType: "house",
        amenities: [
          "WiFi",
          "Beach Access",
          "Garden",
          "Outdoor Workspace",
          "Kitchen",
          "Parking",
        ],
        furnished: true,
        petsAllowed: true,
        availableFrom: new Date("2024-02-10"),
        latitude: -8.3405,
        longitude: 115.092,
        featured: false,
        active: true,
      },
      {
        ownerType: "User",
        owner: customer._id,
        title: "Downtown Loft in Toronto",
        description:
          "Spacious loft in downtown Toronto with modern amenities. Converted warehouse space with high ceilings, exposed brick, and large windows. Located in the Entertainment District, walking distance to CN Tower, restaurants, and nightlife. Perfect for urban professionals.",
        price: 1800,
        currency: "CAD",
        city: "Toronto",
        country: "Canada",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "kitchen",
          },
        ],
        bedrooms: 1,
        bathrooms: 1,
        area: 900,
        areaUnit: "sqft",
        propertyType: "apartment",
        amenities: [
          "WiFi",
          "Gym",
          "Parking",
          "Air Conditioning",
          "Dishwasher",
          "Laundry",
        ],
        furnished: true,
        petsAllowed: true,
        availableFrom: new Date("2024-02-05"),
        latitude: 43.6532,
        longitude: -79.3832,
        featured: false,
        active: true,
      },
      {
        ownerType: "Agency",
        owner: agencies[0]._id,
        title: "Luxury Apartment in Paris",
        description:
          "Elegant 2-bedroom apartment in the heart of Paris, near the Eiffel Tower. Classic Parisian architecture with modern renovations. High ceilings, hardwood floors, and a charming balcony overlooking the city. Perfect for experiencing the Parisian lifestyle.",
        price: 2200,
        currency: "EUR",
        city: "Paris",
        country: "France",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1505843513577-22bb7d21e455?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bathroom",
          },
        ],
        bedrooms: 2,
        bathrooms: 1,
        area: 850,
        areaUnit: "sqft",
        propertyType: "apartment",
        amenities: ["WiFi", "Balcony", "Dishwasher", "Heating", "Elevator"],
        furnished: true,
        petsAllowed: false,
        availableFrom: new Date("2024-03-01"),
        latitude: 48.8566,
        longitude: 2.3522,
        featured: true,
        active: true,
      },
      {
        ownerType: "User",
        owner: customer._id,
        title: "Modern Condo in Tokyo",
        description:
          "Contemporary 1-bedroom condo in Shibuya district. Compact but efficiently designed with smart storage solutions. High-tech amenities, excellent public transport access, and surrounded by restaurants, cafes, and shopping. Ideal for solo professionals or couples.",
        price: 1500,
        currency: "USD",
        city: "Tokyo",
        country: "Japan",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
        ],
        bedrooms: 1,
        bathrooms: 1,
        area: 400,
        areaUnit: "sqft",
        propertyType: "condo",
        amenities: [
          "WiFi",
          "Air Conditioning",
          "Dishwasher",
          "Smart Home",
          "Concierge",
        ],
        furnished: true,
        petsAllowed: false,
        availableFrom: new Date("2024-02-25"),
        latitude: 35.6762,
        longitude: 139.6503,
        featured: false,
        active: true,
      },
      {
        ownerType: "User",
        owner: customer._id,
        title: "Modern Apartment in Mumbai",
        description:
          "Spacious 3-bedroom apartment in Bandra West. Modern amenities, sea views, and excellent connectivity. Located in a premium residential area with access to restaurants, shopping, and entertainment. Perfect for families or professionals.",
        price: 1500,
        currency: "USD",
        city: "Mumbai",
        country: "India",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "kitchen",
          },
        ],
        bedrooms: 3,
        bathrooms: 2,
        area: 1600,
        areaUnit: "sqft",
        propertyType: "apartment",
        amenities: [
          "WiFi",
          "Air Conditioning",
          "Parking",
          "Security",
          "Elevator",
          "Gym",
        ],
        furnished: true,
        petsAllowed: false,
        availableFrom: new Date("2024-03-05"),
        latitude: 19.076,
        longitude: 72.8777,
        featured: false,
        active: true,
      },
      {
        ownerType: "Agency",
        owner: agencies[0]._id,
        title: "Luxury Apartment in Mumbai",
        description:
          "Premium 4-bedroom apartment in Worli with sea views. Modern design with premium finishes, private balcony, and access to world-class amenities. Located in the heart of the city with easy access to business district and entertainment.",
        price: 2500,
        currency: "USD",
        city: "Mumbai",
        country: "India",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bathroom",
          },
          {
            url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "kitchen",
          },
        ],
        bedrooms: 4,
        bathrooms: 3,
        area: 2800,
        areaUnit: "sqft",
        propertyType: "apartment",
        amenities: [
          "Pool",
          "Gym",
          "Concierge",
          "Parking",
          "Balcony",
          "WiFi",
          "Air Conditioning",
          "Security",
        ],
        furnished: true,
        petsAllowed: false,
        availableFrom: new Date("2024-03-20"),
        latitude: 19.0176,
        longitude: 72.8562,
        featured: true,
        active: true,
      },
      {
        ownerType: "User",
        owner: customer._id,
        title: "Modern Apartment in Delhi",
        description:
          "Spacious 3-bedroom apartment in South Delhi. Well-maintained building with modern amenities, close to metro, shopping malls, and restaurants. Perfect for families or professionals working in the capital.",
        price: 1200,
        currency: "USD",
        city: "Delhi",
        country: "India",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "kitchen",
          },
        ],
        bedrooms: 3,
        bathrooms: 2,
        area: 1800,
        areaUnit: "sqft",
        propertyType: "apartment",
        amenities: [
          "WiFi",
          "Air Conditioning",
          "Parking",
          "Security",
          "Elevator",
          "Gym",
        ],
        furnished: true,
        petsAllowed: false,
        availableFrom: new Date("2024-03-01"),
        latitude: 28.6139,
        longitude: 77.209,
        featured: false,
        active: true,
      },
      {
        ownerType: "Agency",
        owner: agencies[1]._id,
        title: "Luxury Villa in Abu Dhabi",
        description:
          "Stunning 5-bedroom villa with private pool and beach access. Ultra-modern design with marble finishes, smart home technology, and premium amenities. Located in a gated community with 24/7 security.",
        price: 6000,
        currency: "AED",
        city: "Abu Dhabi",
        country: "UAE",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bathroom",
          },
          {
            url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "kitchen",
          },
        ],
        bedrooms: 5,
        bathrooms: 5,
        area: 5000,
        areaUnit: "sqft",
        propertyType: "villa",
        amenities: [
          "Pool",
          "Beach Access",
          "Parking",
          "Security",
          "Gym",
          "Garden",
          "Smart Home",
          "WiFi",
        ],
        furnished: true,
        petsAllowed: false,
        availableFrom: new Date("2024-04-01"),
        latitude: 24.4539,
        longitude: 54.3773,
        featured: true,
        active: true,
      },
      {
        ownerType: "User",
        owner: customer._id,
        title: "Cozy Apartment in Manchester",
        description:
          "Charming 2-bedroom apartment in the heart of Manchester. Victorian building with modern interior, fully equipped kitchen, and excellent transport links. Perfect for professionals or small families.",
        price: 1400,
        currency: "GBP",
        city: "Manchester",
        country: "UK",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1505843513577-22bb7d21e455?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "kitchen",
          },
        ],
        bedrooms: 2,
        bathrooms: 1,
        area: 900,
        areaUnit: "sqft",
        propertyType: "apartment",
        amenities: ["WiFi", "Heating", "Dishwasher", "Parking"],
        furnished: true,
        petsAllowed: true,
        availableFrom: new Date("2024-03-05"),
        latitude: 53.4808,
        longitude: -2.2426,
        featured: false,
        active: true,
      },
      {
        ownerType: "Agency",
        owner: agencies[2]._id,
        title: "Luxury Condo in Los Angeles",
        description:
          "Stunning 3-bedroom condo in Beverly Hills with city views. Modern design with premium finishes, private balcony, and access to building amenities. Located in prime location with easy access to shopping and entertainment.",
        price: 4500,
        currency: "USD",
        city: "Los Angeles",
        country: "USA",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bathroom",
          },
        ],
        bedrooms: 3,
        bathrooms: 2,
        area: 2000,
        areaUnit: "sqft",
        propertyType: "condo",
        amenities: [
          "Pool",
          "Gym",
          "Concierge",
          "Parking",
          "Balcony",
          "WiFi",
          "Air Conditioning",
        ],
        furnished: true,
        petsAllowed: false,
        availableFrom: new Date("2024-03-15"),
        latitude: 34.0522,
        longitude: -118.2437,
        featured: true,
        active: true,
      },
      {
        ownerType: "Agency",
        owner: agencies[5]._id,
        title: "Spacious Apartment in Chicago",
        description:
          "Modern 2-bedroom apartment in downtown Chicago with lake views. High-rise building with excellent amenities including gym, pool, and concierge. Walking distance to Millennium Park, shopping, and restaurants.",
        price: 2200,
        currency: "USD",
        city: "Chicago",
        country: "USA",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "kitchen",
          },
          {
            url: "https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bathroom",
          },
        ],
        bedrooms: 2,
        bathrooms: 2,
        area: 1200,
        areaUnit: "sqft",
        propertyType: "apartment",
        amenities: [
          "Pool",
          "Gym",
          "Concierge",
          "Parking",
          "WiFi",
          "Air Conditioning",
          "Dishwasher",
        ],
        furnished: true,
        petsAllowed: true,
        availableFrom: new Date("2024-03-20"),
        latitude: 41.8781,
        longitude: -87.6298,
        featured: false,
        active: true,
      },
      {
        ownerType: "User",
        owner: customer._id,
        title: "Cozy House in San Francisco",
        description:
          "Charming 3-bedroom house in Mission District. Victorian architecture with modern updates, private backyard, and parking. Close to public transport, cafes, and tech companies. Perfect for families or professionals.",
        price: 3200,
        currency: "USD",
        city: "San Francisco",
        country: "USA",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "kitchen",
          },
        ],
        bedrooms: 3,
        bathrooms: 2,
        area: 1800,
        areaUnit: "sqft",
        propertyType: "house",
        amenities: [
          "WiFi",
          "Parking",
          "Garden",
          "Dishwasher",
          "Laundry",
          "Fireplace",
        ],
        furnished: true,
        petsAllowed: true,
        availableFrom: new Date("2024-04-01"),
        latitude: 37.7749,
        longitude: -122.4194,
        featured: true,
        active: true,
      },
      {
        ownerType: "Agency",
        owner: agencies[6]._id,
        title: "Modern Apartment in Birmingham",
        description:
          "Contemporary 2-bedroom apartment in Birmingham city center. Newly renovated with modern finishes, excellent transport links, and close to shopping and entertainment. Ideal for professionals working in the city.",
        price: 1100,
        currency: "GBP",
        city: "Birmingham",
        country: "UK",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1505843513577-22bb7d21e455?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "kitchen",
          },
        ],
        bedrooms: 2,
        bathrooms: 1,
        area: 850,
        areaUnit: "sqft",
        propertyType: "apartment",
        amenities: ["WiFi", "Heating", "Dishwasher", "Parking"],
        furnished: true,
        petsAllowed: false,
        availableFrom: new Date("2024-03-10"),
        latitude: 52.4862,
        longitude: -1.8904,
        featured: false,
        active: true,
      },
      {
        ownerType: "User",
        owner: customer._id,
        title: "Luxury Penthouse in Edinburgh",
        description:
          "Stunning 4-bedroom penthouse with panoramic city views. Modern design with premium finishes, private terrace, and access to building amenities. Located in the heart of Edinburgh's historic center.",
        price: 2800,
        currency: "GBP",
        city: "Edinburgh",
        country: "UK",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bathroom",
          },
          {
            url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "kitchen",
          },
        ],
        bedrooms: 4,
        bathrooms: 3,
        area: 2500,
        areaUnit: "sqft",
        propertyType: "condo",
        amenities: [
          "Pool",
          "Gym",
          "Concierge",
          "Parking",
          "Terrace",
          "WiFi",
          "Heating",
        ],
        furnished: true,
        petsAllowed: false,
        availableFrom: new Date("2024-04-15"),
        latitude: 55.9533,
        longitude: -3.1883,
        featured: true,
        active: true,
      },
      {
        ownerType: "Agency",
        owner: agencies[7]._id,
        title: "Beachfront Apartment in Sharjah",
        description:
          "Beautiful 2-bedroom apartment with direct beach access in Sharjah. Modern amenities, stunning sea views, and close to shopping malls and restaurants. Perfect for families or professionals seeking a beach lifestyle.",
        price: 1800,
        currency: "AED",
        city: "Sharjah",
        country: "UAE",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bathroom",
          },
        ],
        bedrooms: 2,
        bathrooms: 2,
        area: 1400,
        areaUnit: "sqft",
        propertyType: "apartment",
        amenities: [
          "Beach Access",
          "Pool",
          "Gym",
          "Parking",
          "WiFi",
          "Air Conditioning",
          "Balcony",
        ],
        furnished: true,
        petsAllowed: false,
        availableFrom: new Date("2024-03-25"),
        latitude: 25.3573,
        longitude: 55.4033,
        featured: false,
        active: true,
      },
      {
        ownerType: "User",
        owner: customer._id,
        title: "Modern Studio in Bangalore",
        description:
          "Compact studio apartment in Koramangala, Bangalore. Well-designed space with modern amenities, excellent connectivity, and close to IT parks, restaurants, and shopping. Perfect for young professionals.",
        price: 600,
        currency: "USD",
        city: "Bangalore",
        country: "India",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "kitchen",
          },
        ],
        bedrooms: 0,
        bathrooms: 1,
        area: 400,
        areaUnit: "sqft",
        propertyType: "studio",
        amenities: [
          "WiFi",
          "Air Conditioning",
          "Parking",
          "Security",
          "Elevator",
        ],
        furnished: true,
        petsAllowed: false,
        availableFrom: new Date("2024-03-01"),
        latitude: 12.9352,
        longitude: 77.6245,
        featured: false,
        active: true,
      },
      {
        ownerType: "Agency",
        owner: agencies[8]._id,
        title: "Luxury Apartment in Hyderabad",
        description:
          "Premium 3-bedroom apartment in Hitech City, Hyderabad. Modern design with premium finishes, private balcony, and access to world-class amenities. Located in the heart of the IT district with excellent connectivity.",
        price: 1400,
        currency: "USD",
        city: "Hyderabad",
        country: "India",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "kitchen",
          },
          {
            url: "https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bathroom",
          },
        ],
        bedrooms: 3,
        bathrooms: 2,
        area: 1700,
        areaUnit: "sqft",
        propertyType: "apartment",
        amenities: [
          "Pool",
          "Gym",
          "Parking",
          "Security",
          "WiFi",
          "Air Conditioning",
          "Elevator",
          "Balcony",
        ],
        furnished: true,
        petsAllowed: false,
        availableFrom: new Date("2024-04-01"),
        latitude: 17.4486,
        longitude: 78.3908,
        featured: true,
        active: true,
      },
      {
        ownerType: "User",
        owner: customer._id,
        title: "Townhouse in Miami",
        description:
          "Spacious 3-bedroom townhouse in Miami Beach. Modern design with private patio, parking, and close to beaches, restaurants, and nightlife. Perfect for families or professionals seeking the Miami lifestyle.",
        price: 2800,
        currency: "USD",
        city: "Miami",
        country: "USA",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "kitchen",
          },
        ],
        bedrooms: 3,
        bathrooms: 2,
        area: 1600,
        areaUnit: "sqft",
        propertyType: "townhouse",
        amenities: [
          "Parking",
          "Patio",
          "WiFi",
          "Air Conditioning",
          "Dishwasher",
          "Laundry",
        ],
        furnished: true,
        petsAllowed: true,
        availableFrom: new Date("2024-04-10"),
        latitude: 25.7617,
        longitude: -80.1918,
        featured: false,
        active: true,
      },
      {
        ownerType: "Agency",
        owner: agencies[2]._id,
        title: "Luxury Apartment in Dubai Marina",
        description:
          "Stunning 2-bedroom apartment in Dubai Marina with waterfront views. Modern design with premium finishes, private balcony, and access to building amenities including pool, gym, and concierge.",
        price: 3500,
        currency: "AED",
        city: "Dubai",
        country: "UAE",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bathroom",
          },
        ],
        bedrooms: 2,
        bathrooms: 2,
        area: 1500,
        areaUnit: "sqft",
        propertyType: "apartment",
        amenities: [
          "Pool",
          "Gym",
          "Concierge",
          "Parking",
          "Balcony",
          "WiFi",
          "Air Conditioning",
        ],
        furnished: true,
        petsAllowed: false,
        availableFrom: new Date("2024-03-30"),
        latitude: 25.0772,
        longitude: 55.1398,
        featured: true,
        active: true,
      },
    ]);
    console.log(`🏠 ${properties.length} properties created`);

    console.log("\n✅ Seed completed successfully!");
    console.log("\n📝 Login Credentials:");
    console.log("   Admin: admin@demo.com / Admin@123");
    console.log("   Customer: customer@demo.com / Customer@123");
    console.log("   Agencies: sim@demo.com, bank@demo.com, etc. / Agency@123");

    process.exit(0);
  } catch (error) {
    console.error("❌ Seed failed:", error);
    process.exit(1);
  }
};

seedData();
