import dotenv from "dotenv";
import mongoose from "mongoose";
import bcrypt from "bcrypt";
import User from "../models/User.js";
import Agency from "../models/Agency.js";
import Property from "../models/Property.js";
import Country from "../models/Country.js";

dotenv.config();

const seedData = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log("✅ Connected to MongoDB");

    // Clear existing data
    await User.deleteMany({});
    await Agency.deleteMany({});
    await Property.deleteMany({});
    await Country.deleteMany({});
    console.log("🗑️  Cleared existing data");

    // Create countries with currency symbols
    const countries = await Country.create([
      { name: "USA", currency: "$" },
      { name: "UK", currency: "£" },
      { name: "Australia", currency: "A$" },
      { name: "Canada", currency: "C$" },
    ]);
    console.log(`🌍 ${countries.length} countries created`);

    // Create admin user
    const adminPassword = await bcrypt.hash("Admin@123", 10);
    const admin = await User.create({
      name: "Admin User",
      email: "admin@demo.com",
      phone: "+1234567890",
      passwordHash: adminPassword,
      role: "ADMIN",
    });
    console.log("👤 Admin user created: admin@demo.com / Admin@123");

    // Create sample customer
    const customerPassword = await bcrypt.hash("Customer@123", 10);
    const customer = await User.create({
      name: "John Doe",
      email: "customer@demo.com",
      phone: "+1234567891",
      passwordHash: customerPassword,
      role: "CUSTOMER",
    });
    console.log("👤 Customer user created: customer@demo.com / Customer@123");

    // Create sample agencies - only sim, bank, insurance, visa, travel, electricity
    // Only in USA, UK, Australia, Canada with coordinates
    const agencyPassword = await bcrypt.hash("Agency@123", 10);

    const agencies = await Agency.create([
      {
        name: "Global SIM Solutions",
        email: "sim@demo.com",
        passwordHash: agencyPassword,
        category: ["sim"],
        about:
          "We provide international SIM cards and mobile connectivity solutions for travelers. Stay connected in over 190 countries with our reliable network coverage and affordable data plans.",
        phone: "+1-555-0101",
        website: "https://globalsim.example.com",
        address: "123 Tech Plaza, Suite 200",
        city: "New York",
        country: "USA",
        latitude: 40.7128,
        longitude: -74.006,
        logoUrl:
          "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop",
        images: [
          {
            url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "services",
          },
        ],
        isApproved: true,
      },
      {
        name: "SecureBank International",
        email: "bank@demo.com",
        passwordHash: agencyPassword,
        category: ["bank"],
        about:
          "International banking services for expatriates and digital nomads. Multi-currency accounts, low fees, and 24/7 customer support. Trusted by over 100,000 customers worldwide.",
        phone: "+44-20-7946-0958",
        website: "https://securebank.example.com",
        address: "456 Financial District, Canary Wharf",
        city: "London",
        country: "UK",
        latitude: 51.5074,
        longitude: -0.1278,
        logoUrl:
          "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=400&h=400&fit=crop",
        images: [
          {
            url: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "office",
          },
        ],
        isApproved: true,
      },
      {
        name: "TravelGuard Insurance",
        email: "insurance@demo.com",
        passwordHash: agencyPassword,
        category: ["insurance"],
        about:
          "Comprehensive travel and health insurance for international travelers. Coverage includes medical emergencies, trip cancellation, lost luggage, and adventure sports. Get instant quotes and claims processing.",
        phone: "+1-416-555-0123",
        website: "https://travelguard.example.com",
        address: "789 Insurance Tower, Bay Street",
        city: "Toronto",
        country: "Canada",
        latitude: 43.6532,
        longitude: -79.3832,
        logoUrl:
          "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400&h=400&fit=crop",
        images: [
          {
            url: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1554224154-26032844c514?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "reception",
          },
        ],
        isApproved: true,
      },
      {
        name: "FastVisa Services",
        email: "visa@demo.com",
        passwordHash: agencyPassword,
        category: ["visa"],
        about:
          "Quick and reliable visa processing services for all countries. Expert guidance, fast turnaround times, and 99% approval rate. We handle everything from document preparation to embassy submissions.",
        phone: "+1-310-555-0123",
        website: "https://fastvisa.example.com",
        address: "321 Embassy District, Downtown",
        city: "Los Angeles",
        country: "USA",
        latitude: 34.0522,
        longitude: -118.2437,
        logoUrl:
          "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=400&h=400&fit=crop",
        images: [
          {
            url: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "services",
          },
        ],
        isApproved: true,
      },
      {
        name: "Wanderlust Travel Agency",
        email: "travel@demo.com",
        passwordHash: agencyPassword,
        category: ["travel"],
        about:
          "Curated travel experiences and tour packages worldwide. From luxury getaways to budget adventures, we design personalized itineraries. Over 15 years of experience creating unforgettable journeys.",
        phone: "+1-212-555-0123",
        website: "https://wanderlust.example.com",
        address: "555 Broadway, Suite 200",
        city: "New York",
        country: "USA",
        latitude: 40.7589,
        longitude: -73.9851,
        logoUrl:
          "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=400&h=400&fit=crop",
        images: [
          {
            url: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "office",
          },
        ],
        isApproved: true,
      },
      {
        name: "PowerGrid Solutions",
        email: "electricity@demo.com",
        passwordHash: agencyPassword,
        category: ["electricity"],
        about:
          "Professional electricity and utility services for homes and businesses. We help you set up electricity connections, manage utility bills, and provide 24/7 support for all your power needs. Serving customers across major cities.",
        phone: "+61-2-9876-5432",
        website: "https://powergrid.example.com",
        address: "789 Energy Plaza, George Street",
        city: "Sydney",
        country: "Australia",
        latitude: -33.8688,
        longitude: 151.2093,
        logoUrl:
          "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop",
        images: [
          {
            url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "services",
          },
        ],
        isApproved: true,
      },
      {
        name: "UK Visa Experts",
        email: "ukvisa@demo.com",
        passwordHash: agencyPassword,
        category: ["visa"],
        about:
          "Specialized UK visa processing services. Expert guidance for work visas, student visas, family visas, and settlement applications. Fast processing with high success rates. Trusted by thousands of applicants.",
        phone: "+44-20-7946-0123",
        website: "https://ukvisa.example.com",
        address: "123 Mayfair Square",
        city: "London",
        country: "UK",
        latitude: 51.5155,
        longitude: -0.1441,
        logoUrl:
          "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=400&h=400&fit=crop",
        images: [
          {
            url: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "services",
          },
        ],
        isApproved: true,
      },
      {
        name: "Aussie Travel Co",
        email: "ausstravel@demo.com",
        passwordHash: agencyPassword,
        category: ["travel"],
        about:
          "Premier travel agency specializing in Australian destinations and international travel. From outback adventures to beach getaways, we create memorable travel experiences. Book your dream vacation with us today.",
        phone: "+61-3-9876-5432",
        website: "https://aussietravel.example.com",
        address: "456 Collins Street",
        city: "Melbourne",
        country: "Australia",
        latitude: -37.8136,
        longitude: 144.9631,
        logoUrl:
          "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=400&h=400&fit=crop",
        images: [
          {
            url: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "office",
          },
        ],
        isApproved: true,
      },
      {
        name: "Canadian Bank Services",
        email: "canbank@demo.com",
        passwordHash: agencyPassword,
        category: ["bank"],
        about:
          "Comprehensive banking services for newcomers and residents in Canada. Account opening, credit cards, mortgages, and investment services. Helping you manage your finances with ease and confidence.",
        phone: "+1-416-555-0456",
        website: "https://canbank.example.com",
        address: "789 Bay Street, Financial District",
        city: "Toronto",
        country: "Canada",
        latitude: 43.6532,
        longitude: -79.3832,
        logoUrl:
          "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=400&h=400&fit=crop",
        images: [
          {
            url: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "office",
          },
        ],
        isApproved: true,
      },
      {
        name: "Sydney Insurance Group",
        email: "sydneyinsurance@demo.com",
        passwordHash: agencyPassword,
        category: ["insurance"],
        about:
          "Leading insurance provider in Australia. Comprehensive coverage for health, travel, home, and vehicle insurance. Competitive rates and excellent customer service. Protect what matters most to you.",
        phone: "+61-2-9876-0123",
        website: "https://sydneyinsurance.example.com",
        address: "123 Pitt Street",
        city: "Sydney",
        country: "Australia",
        latitude: -33.8688,
        longitude: 151.2093,
        logoUrl:
          "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400&h=400&fit=crop",
        images: [
          {
            url: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1554224154-26032844c514?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "reception",
          },
        ],
        isApproved: true,
      },
      {
        name: "Vancouver SIM Cards",
        email: "vancouversim@demo.com",
        passwordHash: agencyPassword,
        category: ["sim"],
        about:
          "Affordable SIM cards and mobile plans for travelers and residents in Canada. Stay connected with our reliable network coverage. Prepaid and postpaid options available. Visit us for the best deals on mobile connectivity.",
        phone: "+1-604-555-0123",
        website: "https://vancouversim.example.com",
        address: "456 Robson Street",
        city: "Vancouver",
        country: "Canada",
        latitude: 49.2827,
        longitude: -123.1207,
        logoUrl:
          "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop",
        images: [
          {
            url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "services",
          },
        ],
        isApproved: true,
      },
      {
        name: "Manchester Electricity Services",
        email: "manchesterelectricity@demo.com",
        passwordHash: agencyPassword,
        category: ["electricity"],
        about:
          "Professional electricity and utility services in Manchester and surrounding areas. We help with new connections, meter readings, bill management, and energy efficiency solutions. Your trusted partner for all power needs.",
        phone: "+44-161-555-0123",
        website: "https://manchesterelectricity.example.com",
        address: "789 Deansgate",
        city: "Manchester",
        country: "UK",
        latitude: 53.4808,
        longitude: -2.2426,
        logoUrl:
          "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop",
        images: [
          {
            url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "services",
          },
        ],
        isApproved: true,
      },
      // Additional agencies to complete all types in all countries
      {
        name: "American Bank Services",
        email: "usabank@demo.com",
        passwordHash: agencyPassword,
        category: ["bank"],
        about:
          "Premier banking services in the United States. Personal and business accounts, loans, mortgages, and investment services. Trusted by millions of customers nationwide with excellent customer service and competitive rates.",
        phone: "+1-212-555-0456",
        website: "https://usabank.example.com",
        address: "789 Wall Street",
        city: "New York",
        country: "USA",
        latitude: 40.7074,
        longitude: -74.0113,
        logoUrl:
          "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=400&h=400&fit=crop",
        images: [
          {
            url: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "office",
          },
        ],
        isApproved: true,
      },
      {
        name: "USA Insurance Group",
        email: "usainsurance@demo.com",
        passwordHash: agencyPassword,
        category: ["insurance"],
        about:
          "Comprehensive insurance solutions for individuals and businesses in the USA. Health, life, auto, home, and business insurance with competitive rates and excellent coverage. Get protected today with our trusted services.",
        phone: "+1-312-555-0123",
        website: "https://usainsurance.example.com",
        address: "456 Insurance Avenue",
        city: "Chicago",
        country: "USA",
        latitude: 41.8781,
        longitude: -87.6298,
        logoUrl:
          "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400&h=400&fit=crop",
        images: [
          {
            url: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1554224154-26032844c514?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "reception",
          },
        ],
        isApproved: true,
      },
      {
        name: "USA Power Solutions",
        email: "usaelectricity@demo.com",
        passwordHash: agencyPassword,
        category: ["electricity"],
        about:
          "Professional electricity and utility services across the United States. We help with new connections, energy efficiency solutions, bill management, and 24/7 customer support. Your trusted partner for all power needs.",
        phone: "+1-415-555-0123",
        website: "https://usapower.example.com",
        address: "123 Energy Plaza",
        city: "San Francisco",
        country: "USA",
        latitude: 37.7749,
        longitude: -122.4194,
        logoUrl:
          "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop",
        images: [
          {
            url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "services",
          },
        ],
        isApproved: true,
      },
      {
        name: "UK SIM Services",
        email: "uksim@demo.com",
        passwordHash: agencyPassword,
        category: ["sim"],
        about:
          "Affordable SIM cards and mobile plans for travelers and residents in the UK. Stay connected with our reliable network coverage across the country. Prepaid and postpaid options available with excellent customer service.",
        phone: "+44-20-7946-0456",
        website: "https://uksim.example.com",
        address: "321 Oxford Street",
        city: "London",
        country: "UK",
        latitude: 51.5155,
        longitude: -0.1419,
        logoUrl:
          "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop",
        images: [
          {
            url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "services",
          },
        ],
        isApproved: true,
      },
      {
        name: "UK Insurance Partners",
        email: "ukinsurance@demo.com",
        passwordHash: agencyPassword,
        category: ["insurance"],
        about:
          "Leading insurance provider in the United Kingdom. Comprehensive coverage for health, travel, home, vehicle, and business insurance. Competitive rates and excellent customer service. Protect what matters most to you.",
        phone: "+44-20-7946-0789",
        website: "https://ukinsurance.example.com",
        address: "456 Canary Wharf",
        city: "London",
        country: "UK",
        latitude: 51.5045,
        longitude: -0.0185,
        logoUrl:
          "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400&h=400&fit=crop",
        images: [
          {
            url: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1554224154-26032844c514?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "reception",
          },
        ],
        isApproved: true,
      },
      {
        name: "UK Travel Experts",
        email: "uktravel@demo.com",
        passwordHash: agencyPassword,
        category: ["travel"],
        about:
          "Premier travel agency specializing in UK destinations and international travel. From city breaks to countryside escapes, we create memorable travel experiences. Book your dream vacation with us today.",
        phone: "+44-20-7946-0321",
        website: "https://uktravel.example.com",
        address: "789 Regent Street",
        city: "London",
        country: "UK",
        latitude: 51.5104,
        longitude: -0.1396,
        logoUrl:
          "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=400&h=400&fit=crop",
        images: [
          {
            url: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "office",
          },
        ],
        isApproved: true,
      },
      {
        name: "Australian SIM Cards",
        email: "aussim@demo.com",
        passwordHash: agencyPassword,
        category: ["sim"],
        about:
          "Affordable SIM cards and mobile plans for travelers and residents in Australia. Stay connected with our reliable network coverage across the country. Prepaid and postpaid options available with excellent customer service.",
        phone: "+61-2-9876-0456",
        website: "https://aussim.example.com",
        address: "123 George Street",
        city: "Sydney",
        country: "Australia",
        latitude: -33.8688,
        longitude: 151.2093,
        logoUrl:
          "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop",
        images: [
          {
            url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "services",
          },
        ],
        isApproved: true,
      },
      {
        name: "Australian Bank Services",
        email: "ausbank@demo.com",
        passwordHash: agencyPassword,
        category: ["bank"],
        about:
          "Comprehensive banking services for newcomers and residents in Australia. Account opening, credit cards, mortgages, and investment services. Helping you manage your finances with ease and confidence.",
        phone: "+61-3-9876-0456",
        website: "https://ausbank.example.com",
        address: "456 Collins Street",
        city: "Melbourne",
        country: "Australia",
        latitude: -37.8136,
        longitude: 144.9631,
        logoUrl:
          "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=400&h=400&fit=crop",
        images: [
          {
            url: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "office",
          },
        ],
        isApproved: true,
      },
      {
        name: "Australian Visa Services",
        email: "ausvisa@demo.com",
        passwordHash: agencyPassword,
        category: ["visa"],
        about:
          "Specialized Australian visa processing services. Expert guidance for work visas, student visas, family visas, and permanent residency applications. Fast processing with high success rates. Trusted by thousands of applicants.",
        phone: "+61-2-9876-0321",
        website: "https://ausvisa.example.com",
        address: "789 Pitt Street",
        city: "Sydney",
        country: "Australia",
        latitude: -33.8688,
        longitude: 151.2093,
        logoUrl:
          "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=400&h=400&fit=crop",
        images: [
          {
            url: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "services",
          },
        ],
        isApproved: true,
      },
      {
        name: "Canadian Visa Experts",
        email: "canvisa@demo.com",
        passwordHash: agencyPassword,
        category: ["visa"],
        about:
          "Specialized Canadian visa processing services. Expert guidance for work permits, study permits, visitor visas, and permanent residency applications. Fast processing with high success rates. Trusted by thousands of applicants.",
        phone: "+1-416-555-0321",
        website: "https://canvisa.example.com",
        address: "123 Bay Street",
        city: "Toronto",
        country: "Canada",
        latitude: 43.6532,
        longitude: -79.3832,
        logoUrl:
          "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=400&h=400&fit=crop",
        images: [
          {
            url: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "services",
          },
        ],
        isApproved: true,
      },
      {
        name: "Canadian Travel Co",
        email: "cantravel@demo.com",
        passwordHash: agencyPassword,
        category: ["travel"],
        about:
          "Premier travel agency specializing in Canadian destinations and international travel. From mountain adventures to city escapes, we create memorable travel experiences. Book your dream vacation with us today.",
        phone: "+1-604-555-0456",
        website: "https://cantravel.example.com",
        address: "789 Robson Street",
        city: "Vancouver",
        country: "Canada",
        latitude: 49.2827,
        longitude: -123.1207,
        logoUrl:
          "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=400&h=400&fit=crop",
        images: [
          {
            url: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "office",
          },
        ],
        isApproved: true,
      },
      {
        name: "Canadian Power Solutions",
        email: "canelectricity@demo.com",
        passwordHash: agencyPassword,
        category: ["electricity"],
        about:
          "Professional electricity and utility services across Canada. We help with new connections, energy efficiency solutions, bill management, and 24/7 customer support. Your trusted partner for all power needs.",
        phone: "+1-416-555-0789",
        website: "https://canpower.example.com",
        address: "456 Energy Street",
        city: "Toronto",
        country: "Canada",
        latitude: 43.6532,
        longitude: -79.3832,
        logoUrl:
          "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop",
        images: [
          {
            url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "services",
          },
        ],
        isApproved: true,
      },
    ]);
    console.log(
      `🏢 ${agencies.length} agencies created (all with password: Agency@123)`
    );

    // Create sample properties - only in USA, UK, Australia, Canada with currency symbols
    const properties = await Property.create([
      {
        ownerType: "User",
        owner: customer._id,
        title: "Modern Studio in Manhattan",
        description:
          "Beautiful studio apartment in the heart of Manhattan with amazing city views. Fully furnished with modern amenities, high-speed WiFi, and access to building gym and rooftop terrace. Perfect for professionals and digital nomads. Located in SoHo, walking distance to subway, restaurants, and shopping.",
        price: 2500,
        currency: "$",
        city: "New York",
        country: "USA",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "kitchen",
          },
        ],
        bedrooms: 0,
        bathrooms: 1,
        area: 450,
        areaUnit: "sqft",
        propertyType: "studio",
        amenities: ["WiFi", "Gym", "Rooftop", "Air Conditioning", "Dishwasher"],
        furnished: true,
        petsAllowed: false,
        availableFrom: new Date("2024-02-01"),
        latitude: 40.7231,
        longitude: -74.0026,
        featured: true,
        active: true,
      },
      {
        ownerType: "User",
        owner: customer._id,
        title: "Cozy Apartment in London",
        description:
          "Charming 2-bedroom apartment near Hyde Park. Victorian building with modern interior, fully equipped kitchen, and private balcony. Quiet residential area with excellent transport links. Perfect for families or professionals seeking a peaceful retreat in central London.",
        price: 2000,
        currency: "£",
        city: "London",
        country: "UK",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1505843513577-22bb7d21e455?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bathroom",
          },
        ],
        bedrooms: 2,
        bathrooms: 1,
        area: 750,
        areaUnit: "sqft",
        propertyType: "apartment",
        amenities: [
          "WiFi",
          "Balcony",
          "Dishwasher",
          "Washing Machine",
          "Heating",
        ],
        furnished: true,
        petsAllowed: true,
        availableFrom: new Date("2024-02-15"),
        latitude: 51.5074,
        longitude: -0.1278,
        featured: false,
        active: true,
      },
      {
        ownerType: "Agency",
        owner: agencies[5]._id,
        title: "Luxury Apartment in Sydney",
        description:
          "Stunning 3-bedroom apartment with harbor views. Ultra-modern design with floor-to-ceiling windows, premium finishes, and smart home technology. Located in Circular Quay with easy access to Opera House and CBD. Includes private parking, security, and concierge services.",
        price: 3500,
        currency: "A$",
        city: "Sydney",
        country: "Australia",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bathroom",
          },
        ],
        bedrooms: 4,
        bathrooms: 4,
        area: 3500,
        areaUnit: "sqft",
        propertyType: "villa",
        amenities: [
          "Pool",
          "Beach Access",
          "Parking",
          "Security",
          "Concierge",
          "Smart Home",
          "Gym",
          "WiFi",
        ],
        furnished: true,
        petsAllowed: false,
        availableFrom: new Date("2024-03-01"),
        latitude: -33.8688,
        longitude: 151.2093,
        featured: true,
        active: true,
      },
      {
        ownerType: "Agency",
        owner: agencies[7]._id,
        title: "Modern Apartment in Melbourne",
        description:
          "Ultra-modern apartment with panoramic city views. Spacious 2-bedroom unit with private balcony, premium finishes, and access to building amenities. Located in CBD with world-class amenities including gym, pool, and 24/7 concierge.",
        price: 2200,
        currency: "A$",
        city: "Melbourne",
        country: "Australia",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
        ],
        bedrooms: 2,
        bathrooms: 2,
        area: 1200,
        areaUnit: "sqft",
        propertyType: "apartment",
        amenities: [
          "Pool",
          "Gym",
          "Concierge",
          "Parking",
          "Balcony",
          "WiFi",
          "Air Conditioning",
        ],
        furnished: true,
        petsAllowed: false,
        availableFrom: new Date("2024-02-20"),
        latitude: -37.8136,
        longitude: 144.9631,
        featured: true,
        active: true,
      },
      {
        ownerType: "User",
        owner: customer._id,
        title: "Beach House in Gold Coast",
        description:
          "Relaxing beach house perfect for digital nomads. Modern design meets coastal comfort. Steps from the beach, with outdoor workspace, fast WiFi, and stunning ocean views. Surrounded by parks and cafes. Ideal for remote workers seeking inspiration.",
        price: 1800,
        currency: "A$",
        city: "Gold Coast",
        country: "Australia",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "living-room",
          },
        ],
        bedrooms: 2,
        bathrooms: 2,
        area: 1200,
        areaUnit: "sqft",
        propertyType: "house",
        amenities: [
          "WiFi",
          "Beach Access",
          "Garden",
          "Outdoor Workspace",
          "Kitchen",
          "Parking",
        ],
        furnished: true,
        petsAllowed: true,
        availableFrom: new Date("2024-02-10"),
        latitude: -28.0167,
        longitude: 153.4,
        featured: false,
        active: true,
      },
      {
        ownerType: "User",
        owner: customer._id,
        title: "Downtown Loft in Toronto",
        description:
          "Spacious loft in downtown Toronto with modern amenities. Converted warehouse space with high ceilings, exposed brick, and large windows. Located in the Entertainment District, walking distance to CN Tower, restaurants, and nightlife. Perfect for urban professionals.",
        price: 1800,
        currency: "C$",
        city: "Toronto",
        country: "Canada",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "kitchen",
          },
        ],
        bedrooms: 1,
        bathrooms: 1,
        area: 900,
        areaUnit: "sqft",
        propertyType: "apartment",
        amenities: [
          "WiFi",
          "Gym",
          "Parking",
          "Air Conditioning",
          "Dishwasher",
          "Laundry",
        ],
        furnished: true,
        petsAllowed: true,
        availableFrom: new Date("2024-02-05"),
        latitude: 43.6532,
        longitude: -79.3832,
        featured: false,
        active: true,
      },
      {
        ownerType: "Agency",
        owner: agencies[0]._id,
        title: "Luxury Apartment in Vancouver",
        description:
          "Elegant 2-bedroom apartment in the heart of Vancouver, near Stanley Park. Modern architecture with premium renovations. High ceilings, hardwood floors, and a charming balcony overlooking the city. Perfect for experiencing the Vancouver lifestyle.",
        price: 2200,
        currency: "C$",
        city: "Vancouver",
        country: "Canada",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1505843513577-22bb7d21e455?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bathroom",
          },
        ],
        bedrooms: 2,
        bathrooms: 1,
        area: 850,
        areaUnit: "sqft",
        propertyType: "apartment",
        amenities: ["WiFi", "Balcony", "Dishwasher", "Heating", "Elevator"],
        furnished: true,
        petsAllowed: false,
        availableFrom: new Date("2024-03-01"),
        latitude: 49.2827,
        longitude: -123.1207,
        featured: true,
        active: true,
      },
      {
        ownerType: "User",
        owner: customer._id,
        title: "Modern Condo in Brisbane",
        description:
          "Contemporary 1-bedroom condo in Brisbane CBD. Compact but efficiently designed with smart storage solutions. High-tech amenities, excellent public transport access, and surrounded by restaurants, cafes, and shopping. Ideal for solo professionals or couples.",
        price: 1200,
        currency: "A$",
        city: "Brisbane",
        country: "Australia",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
        ],
        bedrooms: 1,
        bathrooms: 1,
        area: 500,
        areaUnit: "sqft",
        propertyType: "condo",
        amenities: [
          "WiFi",
          "Air Conditioning",
          "Dishwasher",
          "Smart Home",
          "Concierge",
        ],
        furnished: true,
        petsAllowed: false,
        availableFrom: new Date("2024-02-25"),
        latitude: -27.4698,
        longitude: 153.0251,
        featured: false,
        active: true,
      },
      {
        ownerType: "User",
        owner: customer._id,
        title: "Modern Apartment in Montreal",
        description:
          "Spacious 3-bedroom apartment in downtown Montreal. Modern amenities, city views, and excellent connectivity. Located in a premium residential area with access to restaurants, shopping, and entertainment. Perfect for families or professionals.",
        price: 1500,
        currency: "C$",
        city: "Montreal",
        country: "Canada",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "kitchen",
          },
        ],
        bedrooms: 3,
        bathrooms: 2,
        area: 1600,
        areaUnit: "sqft",
        propertyType: "apartment",
        amenities: [
          "WiFi",
          "Air Conditioning",
          "Parking",
          "Security",
          "Elevator",
          "Gym",
        ],
        furnished: true,
        petsAllowed: false,
        availableFrom: new Date("2024-03-05"),
        latitude: 45.5017,
        longitude: -73.5673,
        featured: false,
        active: true,
      },
      {
        ownerType: "Agency",
        owner: agencies[0]._id,
        title: "Luxury Apartment in Calgary",
        description:
          "Premium 4-bedroom apartment in Calgary with mountain views. Modern design with premium finishes, private balcony, and access to world-class amenities. Located in the heart of the city with easy access to business district and entertainment.",
        price: 2000,
        currency: "C$",
        city: "Calgary",
        country: "Canada",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bathroom",
          },
          {
            url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "kitchen",
          },
        ],
        bedrooms: 4,
        bathrooms: 3,
        area: 2800,
        areaUnit: "sqft",
        propertyType: "apartment",
        amenities: [
          "Pool",
          "Gym",
          "Concierge",
          "Parking",
          "Balcony",
          "WiFi",
          "Air Conditioning",
          "Security",
        ],
        furnished: true,
        petsAllowed: false,
        availableFrom: new Date("2024-03-20"),
        latitude: 51.0447,
        longitude: -114.0719,
        featured: true,
        active: true,
      },
      {
        ownerType: "Agency",
        owner: agencies[1]._id,
        title: "Luxury House in Perth",
        description:
          "Stunning 5-bedroom house with private pool and garden. Ultra-modern design with premium finishes, smart home technology, and premium amenities. Located in a gated community with 24/7 security.",
        price: 3200,
        currency: "A$",
        city: "Perth",
        country: "Australia",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bathroom",
          },
          {
            url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "kitchen",
          },
        ],
        bedrooms: 5,
        bathrooms: 4,
        area: 4000,
        areaUnit: "sqft",
        propertyType: "house",
        amenities: [
          "Pool",
          "Garden",
          "Parking",
          "Security",
          "Gym",
          "Smart Home",
          "WiFi",
        ],
        furnished: true,
        petsAllowed: false,
        availableFrom: new Date("2024-04-01"),
        latitude: -31.9505,
        longitude: 115.8605,
        featured: true,
        active: true,
      },
      {
        ownerType: "User",
        owner: customer._id,
        title: "Cozy Apartment in Manchester",
        description:
          "Charming 2-bedroom apartment in the heart of Manchester. Victorian building with modern interior, fully equipped kitchen, and excellent transport links. Perfect for professionals or small families.",
        price: 1400,
        currency: "£",
        city: "Manchester",
        country: "UK",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1505843513577-22bb7d21e455?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "kitchen",
          },
        ],
        bedrooms: 2,
        bathrooms: 1,
        area: 900,
        areaUnit: "sqft",
        propertyType: "apartment",
        amenities: ["WiFi", "Heating", "Dishwasher", "Parking"],
        furnished: true,
        petsAllowed: true,
        availableFrom: new Date("2024-03-05"),
        latitude: 53.4808,
        longitude: -2.2426,
        featured: false,
        active: true,
      },
      {
        ownerType: "Agency",
        owner: agencies[3]._id,
        title: "Luxury Condo in Los Angeles",
        description:
          "Stunning 3-bedroom condo in Beverly Hills with city views. Modern design with premium finishes, private balcony, and access to building amenities. Located in prime location with easy access to shopping and entertainment.",
        price: 4500,
        currency: "$",
        city: "Los Angeles",
        country: "USA",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bathroom",
          },
        ],
        bedrooms: 3,
        bathrooms: 2,
        area: 2000,
        areaUnit: "sqft",
        propertyType: "condo",
        amenities: [
          "Pool",
          "Gym",
          "Concierge",
          "Parking",
          "Balcony",
          "WiFi",
          "Air Conditioning",
        ],
        furnished: true,
        petsAllowed: false,
        availableFrom: new Date("2024-03-15"),
        latitude: 34.0522,
        longitude: -118.2437,
        featured: true,
        active: true,
      },
      {
        ownerType: "Agency",
        owner: agencies[0]._id,
        title: "Spacious Apartment in Chicago",
        description:
          "Modern 2-bedroom apartment in downtown Chicago with lake views. High-rise building with excellent amenities including gym, pool, and concierge. Walking distance to Millennium Park, shopping, and restaurants.",
        price: 2200,
        currency: "$",
        city: "Chicago",
        country: "USA",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "kitchen",
          },
          {
            url: "https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bathroom",
          },
        ],
        bedrooms: 2,
        bathrooms: 2,
        area: 1200,
        areaUnit: "sqft",
        propertyType: "apartment",
        amenities: [
          "Pool",
          "Gym",
          "Concierge",
          "Parking",
          "WiFi",
          "Air Conditioning",
          "Dishwasher",
        ],
        furnished: true,
        petsAllowed: true,
        availableFrom: new Date("2024-03-20"),
        latitude: 41.8781,
        longitude: -87.6298,
        featured: false,
        active: true,
      },
      {
        ownerType: "User",
        owner: customer._id,
        title: "Cozy House in San Francisco",
        description:
          "Charming 3-bedroom house in Mission District. Victorian architecture with modern updates, private backyard, and parking. Close to public transport, cafes, and tech companies. Perfect for families or professionals.",
        price: 3200,
        currency: "$",
        city: "San Francisco",
        country: "USA",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "kitchen",
          },
        ],
        bedrooms: 3,
        bathrooms: 2,
        area: 1800,
        areaUnit: "sqft",
        propertyType: "house",
        amenities: [
          "WiFi",
          "Parking",
          "Garden",
          "Dishwasher",
          "Laundry",
          "Fireplace",
        ],
        furnished: true,
        petsAllowed: true,
        availableFrom: new Date("2024-04-01"),
        latitude: 37.7749,
        longitude: -122.4194,
        featured: true,
        active: true,
      },
      {
        ownerType: "Agency",
        owner: agencies[11]._id,
        title: "Modern Apartment in Birmingham",
        description:
          "Contemporary 2-bedroom apartment in Birmingham city center. Newly renovated with modern finishes, excellent transport links, and close to shopping and entertainment. Ideal for professionals working in the city.",
        price: 1100,
        currency: "£",
        city: "Birmingham",
        country: "UK",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1505843513577-22bb7d21e455?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "kitchen",
          },
        ],
        bedrooms: 2,
        bathrooms: 1,
        area: 850,
        areaUnit: "sqft",
        propertyType: "apartment",
        amenities: ["WiFi", "Heating", "Dishwasher", "Parking"],
        furnished: true,
        petsAllowed: false,
        availableFrom: new Date("2024-03-10"),
        latitude: 52.4862,
        longitude: -1.8904,
        featured: false,
        active: true,
      },
      {
        ownerType: "User",
        owner: customer._id,
        title: "Luxury Penthouse in Edinburgh",
        description:
          "Stunning 4-bedroom penthouse with panoramic city views. Modern design with premium finishes, private terrace, and access to building amenities. Located in the heart of Edinburgh's historic center.",
        price: 2800,
        currency: "£",
        city: "Edinburgh",
        country: "UK",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bathroom",
          },
          {
            url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "kitchen",
          },
        ],
        bedrooms: 4,
        bathrooms: 3,
        area: 2500,
        areaUnit: "sqft",
        propertyType: "condo",
        amenities: [
          "Pool",
          "Gym",
          "Concierge",
          "Parking",
          "Terrace",
          "WiFi",
          "Heating",
        ],
        furnished: true,
        petsAllowed: false,
        availableFrom: new Date("2024-04-15"),
        latitude: 55.9533,
        longitude: -3.1883,
        featured: true,
        active: true,
      },
      {
        ownerType: "Agency",
        owner: agencies[10]._id,
        title: "Beachfront Apartment in Vancouver",
        description:
          "Beautiful 2-bedroom apartment with ocean views in Vancouver. Modern amenities, stunning sea views, and close to shopping malls and restaurants. Perfect for families or professionals seeking a coastal lifestyle.",
        price: 1800,
        currency: "C$",
        city: "Vancouver",
        country: "Canada",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bathroom",
          },
        ],
        bedrooms: 2,
        bathrooms: 2,
        area: 1400,
        areaUnit: "sqft",
        propertyType: "apartment",
        amenities: [
          "Ocean Views",
          "Gym",
          "Parking",
          "WiFi",
          "Air Conditioning",
          "Balcony",
        ],
        furnished: true,
        petsAllowed: false,
        availableFrom: new Date("2024-03-25"),
        latitude: 49.2827,
        longitude: -123.1207,
        featured: false,
        active: true,
      },
      {
        ownerType: "User",
        owner: customer._id,
        title: "Modern Studio in Ottawa",
        description:
          "Compact studio apartment in downtown Ottawa. Well-designed space with modern amenities, excellent connectivity, and close to government offices, restaurants, and shopping. Perfect for young professionals.",
        price: 1200,
        currency: "C$",
        city: "Ottawa",
        country: "Canada",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "kitchen",
          },
        ],
        bedrooms: 0,
        bathrooms: 1,
        area: 450,
        areaUnit: "sqft",
        propertyType: "studio",
        amenities: [
          "WiFi",
          "Air Conditioning",
          "Parking",
          "Security",
          "Elevator",
        ],
        furnished: true,
        petsAllowed: false,
        availableFrom: new Date("2024-03-01"),
        latitude: 45.4215,
        longitude: -75.6972,
        featured: false,
        active: true,
      },
      {
        ownerType: "Agency",
        owner: agencies[9]._id,
        title: "Luxury Apartment in Adelaide",
        description:
          "Premium 3-bedroom apartment in Adelaide CBD. Modern design with premium finishes, private balcony, and access to world-class amenities. Located in the heart of the city with excellent connectivity.",
        price: 1800,
        currency: "A$",
        city: "Adelaide",
        country: "Australia",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "kitchen",
          },
          {
            url: "https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bathroom",
          },
        ],
        bedrooms: 3,
        bathrooms: 2,
        area: 1700,
        areaUnit: "sqft",
        propertyType: "apartment",
        amenities: [
          "Pool",
          "Gym",
          "Parking",
          "Security",
          "WiFi",
          "Air Conditioning",
          "Elevator",
          "Balcony",
        ],
        furnished: true,
        petsAllowed: false,
        availableFrom: new Date("2024-04-01"),
        latitude: -34.9285,
        longitude: 138.6007,
        featured: true,
        active: true,
      },
      {
        ownerType: "User",
        owner: customer._id,
        title: "Townhouse in Miami",
        description:
          "Spacious 3-bedroom townhouse in Miami Beach. Modern design with private patio, parking, and close to beaches, restaurants, and nightlife. Perfect for families or professionals seeking the Miami lifestyle.",
        price: 2800,
        currency: "$",
        city: "Miami",
        country: "USA",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "kitchen",
          },
        ],
        bedrooms: 3,
        bathrooms: 2,
        area: 1600,
        areaUnit: "sqft",
        propertyType: "townhouse",
        amenities: [
          "Parking",
          "Patio",
          "WiFi",
          "Air Conditioning",
          "Dishwasher",
          "Laundry",
        ],
        furnished: true,
        petsAllowed: true,
        availableFrom: new Date("2024-04-10"),
        latitude: 25.7617,
        longitude: -80.1918,
        featured: false,
        active: true,
      },
      {
        ownerType: "Agency",
        owner: agencies[2]._id,
        title: "Luxury Apartment in Seattle",
        description:
          "Stunning 2-bedroom apartment in Seattle with waterfront views. Modern design with premium finishes, private balcony, and access to building amenities including pool, gym, and concierge.",
        price: 2800,
        currency: "$",
        city: "Seattle",
        country: "USA",
        photos: [
          {
            url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop",
            isThumbnail: true,
            category: "exterior",
          },
          {
            url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "living-room",
          },
          {
            url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bedroom",
          },
          {
            url: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop",
            isThumbnail: false,
            category: "bathroom",
          },
        ],
        bedrooms: 2,
        bathrooms: 2,
        area: 1500,
        areaUnit: "sqft",
        propertyType: "apartment",
        amenities: [
          "Pool",
          "Gym",
          "Concierge",
          "Parking",
          "Balcony",
          "WiFi",
          "Air Conditioning",
        ],
        furnished: true,
        petsAllowed: false,
        availableFrom: new Date("2024-03-30"),
        latitude: 47.6062,
        longitude: -122.3321,
        featured: true,
        active: true,
      },
    ]);
    console.log(`🏠 ${properties.length} properties created`);

    console.log("\n✅ Seed completed successfully!");
    console.log("\n📝 Login Credentials:");
    console.log("   Admin: admin@demo.com / Admin@123");
    console.log("   Customer: customer@demo.com / Customer@123");
    console.log("   Agencies: sim@demo.com, bank@demo.com, etc. / Agency@123");

    process.exit(0);
  } catch (error) {
    console.error("❌ Seed failed:", error);
    process.exit(1);
  }
};

seedData();
